SET IDENTITY_INSERT [dbo].[CATEGORY_DETAILS] ON
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (10, 1, N'Falls to do an adequate job')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (11, 1, N'Does just enough to get by')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (12, 1, N'Maintains constant level of performance')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (13, 1, N'Very industrious, does more than required')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (16, 1, N'Superior work production record')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (17, 2, N'Uncooperative, antagonistic')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (18, 2, N'Cooperates reluctantly')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (19, 2, N'Cooperates willingly when asked')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (20, 2, N'Cooperates eagerly and cheerfully')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (21, 2, N'Always cooperates eagerly and cheerfully')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (22, 3, N'Usable to follow instructions')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (23, 3, N'Needs repeated detailed instructions')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (24, 3, N'Follows most instructions without difficulty')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (25, 3, N'Follows instructions with no difficulty')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (26, 3, N'Uses initiative in interpreting and following instructions')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (27, 4, N'Frequently rude and unfriendly')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (29, 4, N'Has some difficulty working with others')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (30, 4, N'Usually gets along well with people')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (31, 4, N'Is courteous and tactful with people')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (32, 4, N'Exceptionally well accepted by peers and supervisors')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (33, 5, N'Always attempts to avoid work')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (34, 5, N'Sometimes attempts to avoid work')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (35, 5, N'Does assigned job willingly')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (36, 5, N'Does more than assigned job willingly')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (37, 5, N'Shows resourcefulness in going beyond assigned job')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (38, 6, N'Often absent without good excuse')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (39, 6, N'Frequently late')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (40, 6, N'Usually present and on time')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (41, 6, N'Very prompt and regular, volunteers for overtime when asked')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (42, 6, N'Always prompt and regular, volunteers for overtime when asked')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (43, 7, N'Does almost no acceptable work')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (44, 7, N'Does less than required amount of satisfactory work')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (45, 7, N'Does normal amount of acceptable work')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (46, 7, N'Does more than required amount of neat, accurate work')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (50, 7, N'Shows special attitude for doing neat, accurate work beyond required amount')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (51, 8, N'Untidy or inappropriately groomed')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (52, 8, N'Sometimes neglected of appearance')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (53, 8, N'Satisfactory appearance')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (54, 8, N'Careful about personal appearance')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (55, 8, N'Exceptionally neat, and appropriately groomed')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (56, 9, N'Unreliable')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (57, 9, N'Sometimes fails in obligations')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (58, 9, N'Meets obligations under supervision')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (59, 9, N'Meets obligations under very little supervision')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (60, 9, N'Meets obligations without supervision')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (61, 10, N'Unsatisfactory')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (62, 10, N'Below average')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (63, 10, N'Average')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (64, 10, N'Very good')
INSERT INTO [dbo].[CATEGORY_DETAILS] ([detail_ID], [category_ID], [categoryDetail]) VALUES (65, 10, N'Outstanding')
SET IDENTITY_INSERT [dbo].[CATEGORY_DETAILS] OFF
